name: Deployment Workflow
on:
    push:
      branches:
        - master

jobs:
    pusher:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting step"
              run: echo "This is my first Workflow"
            - name: Logging into Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}